CREATE TABLE cliente (
  cd_cliente INT NOT NULL PRIMARY KEY IDENTITY,
  cd_email VARCHAR(30) NOT NULL,
  nm_cliente VARCHAR(40) NOT NULL,
  nm_sobrenome VARCHAR(40) NOT NULL,
  cd_senha VARCHAR(100) NOT NULL,
  cd_celular VARCHAR(9) NOT NULL,
  cd_ddd_celular VARCHAR(2) NOT NULL,
  cd_cep VARCHAR(8) NOT NULL,
  cd_estado INT NOT NULL FOREIGN KEY REFERENCES estado(cd_estado),
  cd_cidade INT NOT NULL FOREIGN KEY REFERENCES cidade(cd_cidade),
  cd_bairro INT NOT NULL FOREIGN KEY REFERENCES bairro(cd_bairro),
  ds_logradouro VARCHAR(30) NOT NULL,
  cd_login_token VARCHAR(30),
  cd_login_token_mobile VARCHAR(30),
  cd_token_reset_email VARCHAR(6),
  cd_token_reset_celular VARCHAR(6),
  cd_token_reset_senha VARCHAR(30),
  ic_concorda_termos BIT,
  ic_ativo BIT NOT NULL DEFAULT 1,
  ic_situacao_analise BIT DEFAULT 0,
  dt_created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  dt_updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
