CREATE TABLE shopping_bairro.dbo.vendedor (
  cd_vendedor INT NOT NULL PRIMARY KEY IDENITY,
  cd_email VARCHAR(30) NOT NULL,
  nm_vendedor VARCHAR(40) NOT NULL,
  nm_sobrenome VARCHAR(40) NOT NULL,
  cd_senha VARCHAR(100) NOT NULL,
  cd_celular VARCHAR(9) NOT NULL,
  cd_ddd_celular VARCHAR(2) NOT NULL,
  cd_cep VARCHAR(8) NOT NULL,
  cd_estado INT NOT NULL FOREIGN KEY REFERENCES dbo.estados(cd_estado),
  cd_cidade INT NOT NULL FOREIGN KEY REFERENCES dbo.cidades(cd_cidade),
  cd_bairro INT NOT NULL FOREIGN KEY REFERENCES dbo.bairro(cd_bairro),
  ds_logradoura VARCHAR(30) NOT NULL,
  cd_login_token VARCHAR(30),
  cd_login_token_mobile VARCHAR(30),
  cd_token_reset_email VARCHAR(6),
  cd_token_reset_celular VARCHAR(6),
  cd_token_reset_senha VARCHAR(30),
  ic_concorda_termos BIT,
  ic_ativo BIT NOT NULL DEFAULT 1,
  dt_created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  dt_updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
